# Generated by Django 4.1 on 2023-11-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodmusic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_in', models.IntegerField()),
            ],
        ),
    ]
