# Generated by Django 4.1 on 2023-12-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodmusic', '0002_spotifytoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(max_length=255)),
                ('expiry', models.DateTimeField()),
            ],
        ),
    ]
